CREATE DATABASE monitoriaTeste;
use monitoriaTeste;

CREATE TABLE PESSOA(
Id INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
IDADE INT
);

INSERT INTO PESSOA(NOME, IDADE) VALUES('Guilherme', 18);
INSERT INTO PESSOA(NOME, IDADE) VALUES("Alan", 18);
INSERT INTO PESSOA(NOME, IDADE) VALUES("Cris e Greg", 18),("Patrick e Bob Esponja", 18);
SELECT * FROM PESSOA;
UPDATE PESSOA SET NOME = "PERFUME" WHERE Id = 8;

DELETE FROM PESSOA WHERE Id = 7;
ALTER TABLE PESSOA DROP COLUMN IDADE;
DROP TABLE PESSOA;

CREATE TABLE PRODUTO(
ID_Produto INT auto_increment PRIMARY KEY,
NOME_PRODUTO VARCHAR(50),
PRECO FLOAT,
CATEGORIA INT
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR(50)
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTOCATEGORIA FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);

INSERT INTO CATEGORIA(NOME_CATEGORIA) VALUES("Eletronicos"),("Higiene");
select * from categoria;
INSERT INTO PRODUTO(NOME_PRODUTO, PRECO, CATEGORIA) VALUES("COMPUTADOR", 1000.50, 1),("SABONETE", 2, 2);
INSERT INTO PRODUTO(NOME_PRODUTO, PRECO) VALUES("WHATSAPP", 40);

SELECT * FROM PRODUTO;
SELECT * FROM CATEGORIA;
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES("TESTE");

SELECT * FROM PRODUTO INNER JOIN CATEGORIA ON PRODUTO.CATEGORIA = CATEGORIA.ID_CATEGORIA;
SELECT * FROM PRODUTO LEFT JOIN CATEGORIA ON PRODUTO.CATEGORIA = CATEGORIA.ID_CATEGORIA;

CREATE VIEW innerjoinPC as SELECT * FROM PRODUTO INNER JOIN CATEGORIA ON PRODUTO.CATEGORIA = CATEGORIA.ID_CATEGORIA;
CREATE VIEW leftJoinPC as SELECT * FROM PRODUTO LEFT JOIN CATEGORIA ON PRODUTO.CATEGORIA = CATEGORIA.ID_CATEGORIA;

create view trazerpessoas as select * from pessoa where nome like "G%";

select * from leftJoinPC;

/* DELIMITADOR DA PROCEDURE */
DELIMITER $$
/* CRIAÇÃO DA PROCEDURE */
CREATE PROCEDURE sp_inserirPessoa(
in varNOME VARCHAR(50), /* Parametros */
in varIDADE INT /* Parametros (Não esqueça do in) */
)
BEGIN /* COMEÇO DA PROCEDURE/CÓDIGO */
	INSERT INTO PESSOA(NOME, IDADE) VALUES(varNome, varIdade);
END /* FIM DA PROCEDURE/CÓDIGO */
$$ /* FIM DO DELIMITADOR */

SELECT * FROM PESSOA;
/*Chamar Procedure*/
CALL sp_inserirPessoa("CAJU E CASTANHA", 18);

DELIMITER $$
CREATE PROCEDURE sp_atualizarNomeEIdadePessoa(
in varId int,
in varNome varchar(50),
in varIdade int
)
BEGIN
	UPDATE PESSOA SET NOME = varNome, IDADE = varIdade WHERE Id = varId;
END
$$

CALL sp_atualizarNomeEIdadePessoa(2, "Alan2.0", 18)

DELIMITER $$
CREATE PROCEDURE sp_DeletarPessoa(
in varId int
)
BEGIN
	DELETE FROM PESSOA WHERE Id = varId;
END
$$

select * from pessoa;

CALL sp_DeletarPessoa(6);
CALL sp_inserirPessoa("TESTE", 18);